'use client';

import Image from 'next/image';

import Link from './link';

import { useEffect, useRef, useState } from 'react';

import { motion, useReducedMotion } from 'framer-motion';

import { ArrowRight, ArrowUpRight, ChevronDown, X, MapPin, Clock, Phone, Star, Plus, Dumbbell, Wind, Snowflake, Waves, Check, ChevronLeft, ChevronRight } from 'lucide-react';

import { club, images, facilities, classes, articles, clientPlaceholders } from '../lib/content';

import { TrainerCard, TransformationCard, ReviewCard } from './client-content';
import { TrialButton, TrackedLink, ContactActions } from './site';

export function Reveal({children,className=''}:{children:React.ReactNode,className?:string}){const reduced=useReducedMotion();return <motion.div className={className} initial={reduced?false:{opacity:0,y:22}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.08}} transition={{duration:.55,ease:'easeOut'}}>{children}</motion.div>}

export function SectionHeading({eyebrow,children,description}:{eyebrow:string,children:React.ReactNode,description?:string}){return <div className="section-heading"><span className="eyebrow"><span/>{eyebrow}</span><h2>{children}</h2>{description&&<p>{description}</p>}</div>}

function Photo({src,alt,className='',priority=false}:{src:string,alt:string,className?:string,priority?:boolean}){return <Image src={src} alt={alt} fill sizes="(max-width: 700px) 100vw, (max-width: 1100px) 50vw, 65vw" priority={priority} className={`photo ${className}`}/>}

function Hero(){return <section className="hero"><div className="hero-photo"><Photo src={images.hero} alt="Strength equipment and training floor at M&Y Fitness Club" priority/></div><div className="hero-shade"/><div className="container hero-content"><Reveal><span className="eyebrow hero-location"><span/>VAISHALI NAGAR, JAIPUR <i/> OPEN 24/7</span><h1>TRAIN HARD.<br/><span>LIVE STRONGER.</span></h1><p>A space built for your ambition.<br/>Premium training, personal coaching and recovery.<br className="desktop-break"/> All at M&Y Fitness Club.</p><div className="actions"><TrialButton source="hero">Book your free trial</TrialButton><Link className="button secondary" href="#club">Explore the club <ArrowRight size={18}/></Link></div><div className="hero-proof"><div className="star-row" aria-label="Five star symbols"><Star/><Star/><Star/><Star/><Star/></div><strong>4.8<span>/5</span></strong><span>Google rating reported by the club</span></div></Reveal></div><div className="hero-bottom container"><span>YOUR GOALS. YOUR PACE. YOUR CLUB.</span><a href="#club" className="scroll-link">DISCOVER M&Y <ChevronDown size={18}/></a><span className="hero-number">01 / THE CLUB</span></div><div className="hero-side">MOTION & YODDHA — JAIPUR</div></section>}

function Stats(){return <div className="stats container"><div><strong>14,000<span> SQ FT</span></strong><p>SPACE TO GO FURTHER</p></div><div><strong>24<span>/</span>7</strong><p>TRAIN ON YOUR TERMS</p></div><div><strong>4.8<span>/5</span></strong><p>GOOGLE RATING · CLUB WEBSITE</p></div><div className="stat-last"><strong>ONE CLUB.</strong><p>EVERY SIDE OF FITNESS</p></div></div>}

function Introduction(){return <section id="club" className="section container intro"><Reveal className="intro-image"><Photo src={images.floor} alt="Treadmills on the M&Y Fitness Club cardio floor"/><div className="image-label"><span>THE M&Y STANDARD</span><ArrowUpRight/></div><div className="image-corner">MORE ROOM.<br/>MORE POSSIBILITY.</div></Reveal><Reveal className="intro-copy"><SectionHeading eyebrow="MORE THAN A MEMBERSHIP">NOT JUST A GYM.<br/>A COMPLETE<br/><em>FITNESS EXPERIENCE.</em></SectionHeading><p>Find your focus on the training floor. Find your energy in a class. Take a moment to reset in the Wet Lounge.</p><p>From your very first workout to your next personal best, M&Y brings training, coaching and recovery together in one club.</p><div className="intro-tags"><span>TRAIN</span><span>CONNECT</span><span>RECOVER</span></div><Link href="/about/" className="text-link">Explore M&Y <ArrowUpRight size={18}/></Link></Reveal></section>}

export function Facilities(){return <section className="section facilities-section" id="facilities"><div className="container"><Reveal className="section-top"><SectionHeading eyebrow="BUILT FOR YOUR NEXT LEVEL">EVERYTHING YOU NEED.<br/><em>UNDER ONE ROOF.</em></SectionHeading><Link href="/facilities/" className="text-link">Explore our facilities <ArrowUpRight size={18}/></Link></Reveal><div className="facility-grid">{facilities.map((f,i)=><Reveal key={f.name} className={`facility-card facility-${i}`}><Link href={f.href}><Photo src={f.image} alt={f.alt}/><div className="card-shade"/><span className="card-index">0{i+1} / TRAINING ZONE</span><div className="facility-copy"><span className="eyebrow">{f.tag}</span><h3>{f.name}</h3><p>{f.text}</p></div><span className="round-arrow"><ArrowUpRight/></span></Link></Reveal>)}</div><div className="facility-bottom"><span>STRENGTH · CARDIO · FUNCTIONAL · RECOVERY</span><span>ONE SPACE. NO LIMIT TO YOUR AMBITION.</span></div></div></section>}

function Training(){return <section className="section container training"><Reveal><SectionHeading eyebrow="FIND YOUR WAY TO TRAIN">YOUR STARTING POINT.<br/><em>YOUR NEXT CHAPTER.</em></SectionHeading></Reveal><div className="training-list">{[['01','Strength','Build a foundation, one rep at a time.','/facilities/#strength'],['02','Cardio','Find the pace that moves you forward.','/facilities/#cardio'],['03','Functional','Train for movement beyond the gym.','/facilities/#functional'],['04','Personal training','Bring your goals. Build a plan with a coach.','/personal-training/'],['05','Group fitness','Share the energy. Enjoy the challenge.','/classes/']].map(([n,title,text,href])=><Link href={href} key={n}><span className="eyebrow">{n}</span><h3>{title}</h3><p>{text}</p><ArrowUpRight/></Link>)}</div></section>}

export function Classes(){return <section className="section classes-section" id="classes"><div className="container"><Reveal className="section-top"><SectionHeading eyebrow="GOOD ENERGY. GREAT COMPANY.">TRAIN TOGETHER.<br/><em>GET STRONGER TOGETHER.</em></SectionHeading><p className="section-aside">A little motivation goes a long way.<br/>Find yours in the energy of a group.</p></Reveal><div className="class-grid">{classes.map((c,i)=><Reveal key={c.name} className="class-card"><span className="class-number">0{i+1}</span><div className="class-symbol">{i===0?<Waves/>:i===1?<Wind/>:i===2?<Dumbbell/>:<Plus/>}</div><span className="eyebrow">{c.label}</span><h3>{c.name}</h3><p>{c.text}</p><Link href={`/classes/#${c.name.toLowerCase().replace(' ','-')}`} className="text-link">Explore class <ArrowUpRight size={18}/></Link></Reveal>)}</div><div className="center-action"><Link href="/classes/" className="button secondary">View classes <ArrowRight size={18}/></Link><span>Ask the team for current class times and availability.</span></div></div></section>}

export function PersonalTraining(){return <section className="section container personal-training" id="personal-training"><Reveal className="pt-copy"><SectionHeading eyebrow="PERSONAL TRAINING AT M&Y">YOUR GOALS.<br/>YOUR COACH.<br/><em>YOUR PLAN.</em></SectionHeading><p>Start with where you are. Work towards where you want to be. Get personal guidance that makes every session count.</p><ul className="benefit-list">{['A conversation about your goals','A program built around you','Guidance on movement and technique','Progress reviews and accountability'].map(t=><li key={t}><Check size={17}/>{t}</li>)}</ul><TrialButton source="pt">Book a PT consultation</TrialButton></Reveal><Reveal className="pt-image"><Photo src={images.coaching} alt="A training session photographed on the M&Y gym floor"/><div className="image-label"><span>GUIDANCE THAT GOES WITH YOU.</span><ArrowUpRight/></div></Reveal></section>}

export function Recovery(){return <section className="recovery section"><div className="container recovery-grid"><Reveal><span className="eyebrow">THE WET LOUNGE</span><h2>TRAIN.<br/><em>RECOVER.</em><br/>REPEAT.</h2><p>Make space for the quieter side of fitness.<br/>Step off the floor and into your reset.</p><Link href="/facilities/#recovery" className="text-link">Discover recovery at M&Y <ArrowUpRight size={18}/></Link></Reveal><div className="recovery-options">{[[Waves,'01','Steam','A moment to slow down after your session.'],[Snowflake,'02','Ice bath','Explore the club’s cold-water recovery facility.'],[Wind,'03','AI massage','Unwind in the club’s dedicated wellness space.']].map(([Icon,n,title,text])=>{const I=Icon as typeof Waves;return <Reveal key={String(n)} className="recovery-item"><I size={30}/><div><span className="eyebrow">{String(n)} / RESET</span><h3>{String(title)}</h3><p>{String(text)}</p></div></Reveal>})}<small>Ask the team about access, availability and suitability before using recovery facilities.</small></div></div><span className="recovery-watermark" aria-hidden="true">RESET</span></section>}

function Progress(){return <section className="section container progress"><Reveal><SectionHeading eyebrow="EVERY JOURNEY STARTS SOMEWHERE">REAL PEOPLE.<br/><em>REAL PROGRESS.</em></SectionHeading><p>Your progress is personal. Whether it’s your first confident workout or a new strength milestone, start by talking to the team about what matters to you.</p><TrialButton className="secondary" source="progress">Start your journey</TrialButton></Reveal>{clientPlaceholders.transformations.length>0?<div className="client-card-grid">{clientPlaceholders.transformations.map(r=><TransformationCard key={r.name} result={r}/>)}</div>:<div className="progress-editorial"><span className="eyebrow">YOUR NEXT PERSONAL BEST</span><span className="progress-word">YOU<br/><em>VS.</em><br/>YOU.</span><span className="eyebrow">SHOW UP FOR YOURSELF.</span></div>}</section>}

function Trainers(){return <section className="section container trainers"><Reveal className="section-top"><SectionHeading eyebrow="THE PEOPLE IN YOUR CORNER">MEET THE TEAM<br/><em>BEHIND YOUR PROGRESS.</em></SectionHeading><div className="section-aside"><p>Meet the coaching team in person. Share your goals and find the right guidance for your training.</p><TrialButton className="secondary" source="pt">Meet a coach</TrialButton></div></Reveal>{clientPlaceholders.trainers.length>0&&<div className="client-card-grid">{clientPlaceholders.trainers.map(t=><TrainerCard key={t.name} trainer={t}/>)}</div>}<div className="team-band"><div><span className="eyebrow">FROM THE FIRST CONVERSATION</span><h3>A human approach.<br/>A plan with purpose.</h3></div><p>Technique. Consistency. Confidence.<br/>Explore personal training at M&Y.</p><Link href="/personal-training/" className="round-arrow" aria-label="Explore personal training"><ArrowUpRight/></Link></div></section>}

export function Membership(){return <section className="section membership-section" id="membership"><div className="container"><Reveal className="section-top"><SectionHeading eyebrow="MAKE FITNESS YOUR ROUTINE">CHOOSE YOUR WAY<br/><em>TO TRAIN.</em></SectionHeading><p className="section-aside">Your schedule. Your goals. Your club.<br/>Speak to the team for current plans and pricing.</p></Reveal><div className="membership-grid"><Reveal className="membership-card"><span className="eyebrow">START WITH A VISIT</span><h3>Experience M&Y</h3><p>See the space. Meet the team. Find out how the club fits your goals.</p><ul><li><Check/>Explore the training floor</li><li><Check/>Discuss your fitness goals</li><li><Check/>Ask about classes and recovery</li></ul><TrialButton className="secondary" source="membership-trial">Book free trial</TrialButton></Reveal><Reveal className="membership-card featured"><span className="membership-label">YOUR NEXT CHAPTER</span><span className="eyebrow">BUILD YOUR ROUTINE</span><h3>Make it your club.</h3><p>Find the membership that works for you. Get the latest options directly from M&Y.</p><ul><li><Check/>24/7 training access</li><li><Check/>14,000 sq ft club environment</li><li><Check/>Coaching and class options</li></ul><TrackedLink href={`tel:${club.phone}`} event="membership_click" source="membership" className="button">Get membership details <ArrowUpRight size={18}/></TrackedLink><small>Pricing, inclusions and service hours confirmed by the club.</small></Reveal></div></div></section>}

function Reviews(){return <section className="section container reviews"><Reveal><span className="eyebrow">THE CLUB COMMUNITY</span><h2>LOVED BY OUR<br/><em>FITNESS COMMUNITY.</em></h2></Reveal>{clientPlaceholders.reviews.length>0&&<div className="client-card-grid">{clientPlaceholders.reviews.map(r=><ReviewCard key={r.name} review={r}/>)}</div>}<div className="rating-block"><strong>4.8<span>/5</span></strong><div className="star-row"><Star/><Star/><Star/><Star/><Star/></div><p>Google rating reported on the M&Y website.<br/>Visit the club’s Maps listing for current reviews.</p><a href={club.maps} target="_blank" rel="noopener noreferrer" className="text-link">Read community reviews <ArrowUpRight size={18}/></a></div></section>}

const gallery=[{image:images.equipment,title:'Room for your ambition',alt:'Strength machines and free weights at M&Y'},{image:images.floor,title:'Find your rhythm',alt:'M&Y cardio floor with treadmills'},{image:images.training,title:'Every rep has a purpose',alt:'Member training with coaching in the M&Y website video poster'},{image:images.coaching,title:'A little guidance. A lot of possibility.',alt:'Training session on the M&Y gym floor'}];

export function Gallery(){const [active,setActive]=useState<number|null>(null);const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{if(active!==null)ref.current?.showModal();else ref.current?.close()},[active]);return <section className="section container" id="gallery"><Reveal className="section-top"><SectionHeading eyebrow="TAKE A LOOK AROUND">INSIDE <em>M&Y.</em></SectionHeading><a href={club.instagram} target="_blank" rel="noopener noreferrer" className="text-link">Follow the club <ArrowUpRight size={18}/></a></Reveal><div className="gallery-grid">{gallery.map((g,i)=><button key={g.title} className={`gallery-item gallery-${i}`} onClick={()=>setActive(i)} aria-label={`View photo: ${g.title}`}><Photo src={g.image} alt={g.alt}/><span>{g.title}<Plus size={20}/></span></button>)}</div><dialog ref={ref} aria-label="Club photo gallery" className="lightbox" onCancel={()=>setActive(null)}><button className="icon-button close" aria-label="Close gallery" onClick={()=>setActive(null)}><X/></button>{active!==null&&<><div className="lightbox-image"><Photo src={gallery[active].image} alt={gallery[active].alt}/></div><div className="lightbox-bottom"><button className="icon-button" aria-label="Previous photo" onClick={()=>setActive((active+gallery.length-1)%gallery.length)}><ChevronLeft/></button><p>{gallery[active].title} <span>{active+1} / {gallery.length}</span></p><button className="icon-button" aria-label="Next photo" onClick={()=>setActive((active+1)%gallery.length)}><ChevronRight/></button></div></>}</dialog></section>}

export function CTA(){return <section className="cta-section"><div className="container"><Reveal><span className="eyebrow">THE FIRST STEP IS YOURS.</span><h2>YOUR STRONGER SELF<br/><span>STARTS HERE.</span></h2><p>Experience M&Y Fitness Club before you commit.</p><TrialButton className="dark" source="bottom-cta">Claim your free trial</TrialButton><small>Your day pass is subject to club confirmation and availability.</small></Reveal><ArrowUpRight className="cta-big-arrow" aria-hidden="true"/></div></section>}

export function Contact(){return <section className="section container contact" id="contact"><Reveal><SectionHeading eyebrow="YOUR CLUB. YOUR NEIGHBOURHOOD.">FIND US IN<br/><em>VAISHALI NAGAR.</em></SectionHeading><p>Come for a look around.<br/>Leave with a reason to come back.</p><div className="contact-details"><div><MapPin/><div><span className="eyebrow">THE ADDRESS</span><p>{club.address}</p></div></div><div><Clock/><div><span className="eyebrow">YOUR TIME TO TRAIN</span><p>24/7 gym access<br/><small>Contact the team for staffed hours and class times.</small></p></div></div><div><Phone/><div><span className="eyebrow">LET’S TALK</span><TrackedLink href={`tel:${club.phone}`} event="call_click" source="contact-number">{club.displayPhone}</TrackedLink><a href={`mailto:${club.email}`}>{club.email}</a></div></div></div><ContactActions/></Reveal><div className="location-card"><div className="map-grid"/><span className="map-road road-one">VAISHALI NAGAR</span><span className="map-road road-two">JAIPUR</span><div className="map-pin"><MapPin size={36}/><strong>M&Y</strong><span>FITNESS CLUB</span></div><span className="map-label">LOCATION OVERVIEW · ILLUSTRATIVE</span><TrackedLink href={club.maps} external event="directions_click" source="map-card" className="map-cta">Open exact location in Google Maps <ArrowUpRight size={18}/></TrackedLink></div></section>}

export function Journal(){return <section className="section container journal"><SectionHeading eyebrow="THE M&Y JOURNAL">IDEAS TO KEEP<br/><em>YOU MOVING.</em></SectionHeading><div className="journal-grid">{articles.map(a=><a href={a.href} key={a.title} target="_blank" rel="noopener noreferrer"><div className="journal-image"><Photo src={a.image} alt="Image from the M&Y fitness journal"/></div><span className="eyebrow">{a.category}</span><h3>{a.title}<ArrowUpRight size={22}/></h3><p>Read the original article on the club website.</p></a>)}</div><a href="https://www.mnyfitnessclub.com/blog" target="_blank" rel="noopener noreferrer" className="text-link">Explore the existing journal <ArrowUpRight size={18}/></a></section>}

export function HomePage(){return <><Hero/><Stats/><Introduction/><Facilities/><Training/><Classes/><PersonalTraining/><Recovery/><Progress/><Trainers/><Membership/><Reviews/><Gallery/><CTA/><Contact/></>}

const pageTitles:Record<string,{eyebrow:string,title:React.ReactNode,copy:string}>={

 about:{eyebrow:'THIS IS M&Y',title:<>BUILT FOR MORE.<br/><em>BUILT AROUND YOU.</em></>,copy:'Training, coaching, community and recovery. Discover the M&Y experience in Vaishali Nagar, Jaipur.'},

 facilities:{eyebrow:'SPACE TO FIND YOUR STRIDE',title:<>ONE CLUB.<br/><em>MORE POSSIBILITY.</em></>,copy:'Explore 14,000 sq ft of training space, dedicated zones and the Wet Lounge.'},

 classes:{eyebrow:'FIND YOUR PEOPLE. FIND YOUR ENERGY.',title:<>BETTER<br/><em>TOGETHER.</em></>,copy:'Zumba, Power Yoga, HIIT and CrossFit. Discover a new way to make movement part of your routine.'},

 'personal-training':{eyebrow:'PERSONAL TRAINING IN JAIPUR',title:<>A GOAL IS PERSONAL.<br/><em>YOUR TRAINING, TOO.</em></>,copy:'Discuss your goals with the club’s coaching team and explore a program built around you.'},

 membership:{eyebrow:'BELONG AT M&Y',title:<>MAKE ROOM<br/><em>FOR YOURSELF.</em></>,copy:'Explore the club, discuss your goals and ask the team for current membership options.'},

 gallery:{eyebrow:'THE CLUB, UP CLOSE',title:<>SEE THE SPACE.<br/><em>FEEL THE ENERGY.</em></>,copy:'Photography from the M&Y website. Your next chapter could start here.'},

 contact:{eyebrow:'VAISHALI NAGAR, JAIPUR',title:<>COME ON IN.<br/><em>LET’S GET STARTED.</em></>,copy:'Talk to the team, request a day pass or plan your first visit.'},

 blog:{eyebrow:'THE M&Y JOURNAL',title:<>STAY CURIOUS.<br/><em>KEEP MOVING.</em></>,copy:'Explore the club’s existing training insights and fitness stories.'},

};

function FAQ(){return <section className="section container faq"><SectionHeading eyebrow="BEFORE YOUR FIRST VISIT">A FEW THINGS<br/><em>TO KNOW.</em></SectionHeading><div>{[['Where is M&Y Fitness Club?','The club is on the 2nd Floor, Vaishali Nagar, Near Gurudwara, Jaipur. Use the club’s Google Maps link for directions.'],['Can I try the gym before joining?','The existing M&Y website offers a free day pass. Request a visit and the club will confirm availability and applicable terms.'],['Is the gym open 24/7?','M&Y’s website reports 24/7 gym access. Contact the team for staffed hours, class times and recovery-facility availability.'],['How much does membership cost?','Current membership pricing and plan inclusions should be confirmed directly with the club. Call +91 96602 23315.']].map(([q,a])=><details key={q}><summary>{q}<Plus size={18}/></summary><p>{a}</p></details>)}</div></section>}

export function InteriorPage({slug}:{slug:string}){

 if(slug==='privacy'||slug==='terms')return <section className="container legal section"><span className="eyebrow">M&Y FITNESS CLUB</span><h1>{slug==='privacy'?'Privacy information':'Trial & enquiry terms'}</h1>{slug==='privacy'?<><p>This redesign prepares an enquiry draft in your browser unless the club has connected a lead endpoint. Draft details are not stored by this website. Sending an email or using the original booking page submits information through those services.</p><p>If a lead endpoint is enabled, your name, phone number, fitness goal and optional visit time are sent to the configured club service for responding to your enquiry. This website does not include analytics or advertising IDs.</p><p>External services, including Google Maps and social platforms, apply their own privacy policies. Contact {club.email} with questions about club-held information.</p></>:<><p>A free day-pass request is an enquiry. Availability, eligibility, access inclusions and booking confirmation are determined by M&Y Fitness Club. An enquiry does not create a confirmed reservation or membership.</p><p>Membership prices, recovery access, staffed hours and class schedules must be confirmed with the club before purchasing or visiting.</p></>}<p className="legal-draft">Client review required before public launch: confirm the club’s data retention, processor disclosures and formal legal policies.</p><Link href="/contact/" className="text-link">Contact the club <ArrowUpRight size={18}/></Link></section>;

 const p=pageTitles[slug];return <><section className="page-hero container"><div className="breadcrumb"><Link href="/">Home</Link><span>/</span><span>{slug.replace('-',' ')}</span></div><Reveal><span className="eyebrow">{p.eyebrow}</span><h1>{p.title}</h1><p>{p.copy}</p><TrialButton source={`page-${slug}`}>Book free trial</TrialButton></Reveal></section>{slug==='about'&&<><Stats/><Introduction/><Trainers/><Reviews/><FAQ/></>}{slug==='facilities'&&<><Facilities/><section className="container section facility-details">{facilities.map((f,i)=><div id={['strength','cardio','functional'][i]} key={f.name}><span className="eyebrow">0{i+1} / TRAINING ZONE</span><h2>{f.name}</h2><p>{f.text}</p></div>)}</section><div id="recovery"><Recovery/></div></>}{slug==='classes'&&<><Classes/><section className="container section class-detail-grid">{classes.map(c=><div id={c.name.toLowerCase().replace(' ','-')} key={c.name}><h2>{c.name}</h2><p>{c.text}</p><TrackedLink href={`tel:${club.phone}`} event="call_click" source="class-schedule" className="text-link">Ask about {c.name} times <ArrowUpRight size={18}/></TrackedLink></div>)}</section></>}{slug==='personal-training'&&<><PersonalTraining/><Trainers/><FAQ/></>}{slug==='membership'&&<><Membership/><FAQ/></>}{slug==='gallery'&&<Gallery/>}{slug==='contact'&&<><Contact/><FAQ/></>}{slug==='blog'&&<Journal/>}{slug!=='contact'&&<CTA/>}</>;

}
